name=EM2M-ESP32-Driver
version=1.0.0
author=Dhruv K
maintainer=Dhruv K
setence=ESP32 driver for Selec EM2M Energy Meter using Modbus RTU
paragraph=LightWeight HAL-style for reading voltage, current, power factor, frequency and other parameters from Selec EM2M energy meter via RS485 Modbus.
category=Communication
url=https://github.com/dhruvkotian/em2m-esp32-modbus
architectures=esp32
depends=ModbusMaster
